version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    networks:
      - db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=smart_gallery
      - POSTGRES_USER=smart_gallery
      - POSTGRES_PASSWORD=smart_gallery_password
  redis:
    image: redis:6-alpine
    networks:
      - redis
    ports:
      - 127.0.0.1:6379:6379

networks:
  db:
  redis:
