version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    networks:
      - db
    environment:
      - POSTGRES_DB=smart_gallery
      - POSTGRES_USER=smart_gallery
      - POSTGRES_PASSWORD=smart_gallery_password
  redis:
    image: redis:6-alpine
    networks:
      - redis
  web_server:
    build:
      context: .
      dockerfile: Dockerfile.web_server
    networks:
      - db
      - redis
      - web_server
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=smart_gallery
      - POSTGRES_USER=smart_gallery
      - POSTGRES_PASSWORD=smart_gallery_password
      - REDIS_HOST=redis
  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.worker
    networks:
      - db
      - redis
      - web_server
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=smart_gallery
      - POSTGRES_USER=smart_gallery
      - POSTGRES_PASSWORD=smart_gallery_password
      - REDIS_HOST=redis

networks:
  db:
  redis:
  web_server:
