FROM python:3.7-slim

ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
RUN apt-get update && apt-get -y install python3.7-dev gcc python3-dev libpq-dev
COPY requirements.txt /app/.
RUN pip3 install -r requirements.txt
COPY . /app/.

ENTRYPOINT [ "python3", "main/worker.py" ]