FROM python:3.7-slim

ENV PYTHONUNBUFFERED 1
ENV APP_STATIC_DIR /static
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/.
RUN pip3 install -r requirements.txt
COPY . /app/.

ENTRYPOINT [ "python3", "main/web_server.py" ]